---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infra.virtrigaud.io
  resources:
  - providers
  - virtualmachines
  - vmmigrations
  - vmsnapshots
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infra.virtrigaud.io
  resources:
  - providers/finalizers
  - virtualmachines/finalizers
  - vmmigrations/finalizers
  - vmsnapshots/finalizers
  verbs:
  - update
- apiGroups:
  - infra.virtrigaud.io
  resources:
  - providers/status
  - virtualmachines/status
  - vmmigrations/status
  - vmsnapshots/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - infra.virtrigaud.io
  resources:
  - vmclasses
  - vmimages
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infra.virtrigaud.io
  resources:
  - vmnetworkattachments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - infra.virtrigaud.io.infra.virtrigaud.io
  resources:
  - vmclasses
  - vmimages
  - vmnetworkattachments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infra.virtrigaud.io.infra.virtrigaud.io
  resources:
  - vmclasses/finalizers
  - vmimages/finalizers
  - vmnetworkattachments/finalizers
  verbs:
  - update
- apiGroups:
  - infra.virtrigaud.io.infra.virtrigaud.io
  resources:
  - vmclasses/status
  - vmimages/status
  - vmnetworkattachments/status
  verbs:
  - get
  - patch
  - update
