processor:
  # Ignore fields inherited from TypeMeta and ObjectMeta
  ignoreFields:
    - TypeMeta
    - ObjectMeta
    - ListMeta

render:
  # Group CRDs by their group
  groupByKind: false

  # Custom rendering options
  kubernetesVersion: "1.32"

  # Add links to external types
  externalPackages:
    - name: k8s.io/api/core/v1
      goModulePath: k8s.io/api
    - name: k8s.io/apimachinery/pkg/apis/meta/v1
      goModulePath: k8s.io/apimachinery
